# Generated by Django 4.1.7 on 2023-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0003_alter_agenda_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
