# Generated by Django 4.1.7 on 2023-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0003_benevole_client_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
