# Generated by Django 4.1.7 on 2023-03-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
