# Generated by Django 4.1.7 on 2023-03-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0005_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benevole',
            old_name='address',
            new_name='addresse',
        ),
        migrations.RenameField(
            model_name='benevole',
            old_name='first_name',
            new_name='nom_de_famille',
        ),
        migrations.RenameField(
            model_name='benevole',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='addresse',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='is_bénévole',
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='benevole',
            name='prenom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='nom_de_famille',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
