# Generated by Django 4.1.7 on 2023-03-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0006_rename_address_benevole_addresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benevole',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
