# Generated by Django 4.1.7 on 2023-04-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0008_status_userprofile_benevole_status_client_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
