# Generated by Django 4.1.7 on 2023-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0009_remove_userprofile_status_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='lieu',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
