# Generated by Django 4.1.7 on 2023-04-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0010_alter_agenda_lieu_alter_agenda_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='lieu',
            field=models.CharField(max_length=100),
        ),
    ]
