# Generated by Django 4.1.7 on 2023-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0011_alter_agenda_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tel',
            field=models.CharField(max_length=100),
        ),
    ]
