# Generated by Django 4.1.7 on 2023-04-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0012_alter_agenda_nom_alter_agenda_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benevole',
            old_name='addresse',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='addresse',
            new_name='adresse',
        ),
    ]
