# Generated by Django 4.1.7 on 2023-04-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0013_rename_addresse_benevole_adresse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benevole',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='benevole',
            old_name='nom_de_famille',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='benevole',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom_de_famille',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.AddField(
            model_name='benevole',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
