# Generated by Django 4.1.7 on 2023-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0014_rename_adresse_benevole_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='is_bénévole',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
