# Generated by Django 4.1.7 on 2023-04-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0015_benevole_is_bénévole_client_is_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='nom',
            new_name='nom_utilisateur',
        ),
    ]
