# Generated by Django 4.1.7 on 2023-04-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0017_agenda_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benevole',
            old_name='is_bénévole',
            new_name='is_benevole',
        ),
    ]
